#
# Knockout Web site config
#
# ---
#
# Application Cache
appcache:
  target: ko.appcache
  manifest: |
    CACHE MANIFEST
    # $ISOTIME
    index.html
    favicon.ico
    images/logo.svg
    build/templates.html
    build/styles.css
    build/libs.js
    build/app.js
    images/hourglass.gif

    # Ace
    bower_components/ace-builds/src/ace.js
    bower_components/ace-builds/src/mode-javascript.js
    bower_components/ace-builds/src/mode-html.js
    bower_components/ace-builds/src/theme-solarized_dark.js
    bower_components/ace-builds/src/theme-monokai.js
    bower_components/ace-builds/src/worker-javascript.js
    bower_components/ace-builds/src/worker-html.js

    NETWORK:
    *


# HTML Templates
templates:
  src: templates/*
  dest: build/
  filename: templates.html


# Javascript libraries
libs.js:
  dest: build/
  filename: libs.js
  src:
    - node_modules/gulp-babel/node_modules/babel-core/browser-polyfill.js
    - node_modules/jquery/dist/jquery.js
    - node_modules/knockout/build/output/knockout-latest.js
    - bower_components/knockout.punches/knockout.punches.js
    - bower_components/html5-history-api/history.js


# Our JS application
app.js:
  src: src/**/*.js
  dest: build/
  name: app.js
  babel-config:
    modules: common

# less => css
less:
  src: less/styles.less
  dest: build/
