#
# Knockout Web site config
#
# ---
#
# Application Cache
appcache:
  target: ko.appcache
  manifest: |
    CACHE MANIFEST
    # $ISOTIME
    index.html
    build/templates.html
    build/styles.css
    build/libs.js
    build/app.js
    images/hourglass.gif

    NETWORK:
    *


# HTML Templates
templates:
  src: templates/*
  dest: build/
  filename: templates.html


# Javascript libraries
libs.js:
  dest: build/
  filename: libs.js
  src:
    - node_modules/gulp-babel/node_modules/babel-core/browser-polyfill.js
    - node_modules/jquery/dist/jquery.js
    - node_modules/knockout/build/output/knockout-latest.js
    - src/knockout.punches.js


# Our JS application
app.js:
  src: src/**/*.js
  dest: build/
  name: app.js
  babel-config:
    modules: common

# less => css
less:
  src: less/styles.less
  dest: build/
