#
# Knockout Web site config
#
# ---
#
# Application Cache
appcache:
  target: ko.appcache
  manifest: |
    CACHE MANIFEST
    # $ISOTIME
    index.html
    favicon.ico
    images/logo.svg
    build/templates.html
    build/styles.css
    build/libs.js
    build/app.js
    build/examples.json
    build/plugins.json
    images/hourglass.gif
    https://fonts.googleapis.com/css?family=Lato:400,700,400italic
    //maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css

    # Ace -- these to-be Workers need to be available in separate
    # scripts.
    worker-javascript.js
    worker-html.js

    FALLBACK:
    / index.html

    NETWORK:
    *


# HTML Templates
templates:
  src: templates/**/*.html
  dest: build/
  filename: templates.html


# Markdown templates (processed on browser)
markdown:
  src: markdown/**/*.md
  dest: build/
  filename: markdown.html
  header: >
    <script type='text/x-markdown' id='<%=path.basename(file.path, '.md')%>' data-markdown
      data-kind='<%= file.frontMatter.kind %>'
      data-title='<%= file.frontMatter.title %>'
      data-cat='<%= file.frontMatter.cat %>'
      data-subcat='<%= file.frontMatter.subCat %>'>
  footer: >
    </script>

# Javascript libraries
libs.js:
  dest: build/
  filename: libs.js
  src:
    - node_modules/gulp-babel/node_modules/babel-core/browser-polyfill.js
    - node_modules/jquery/dist/jquery.js
    - node_modules/knockout/build/output/knockout-latest.js
    - bower_components/knockout.punches/knockout.punches.js
    - node_modules/knockout-transformations/dist/knockout-transformations.js
    - bower_components/marked/marked.min.js
    - bower_components/ace-builds/src/ace.js
    - bower_components/ace-builds/src/mode-javascript.js
    - bower_components/ace-builds/src/mode-html.js
    - bower_components/ace-builds/src/theme-solarized_dark.js
    - bower_components/ace-builds/src/theme-solarized_light.js
    - bower_components/ace-builds/src/theme-tomorrow.js
    - bower_components/ace-builds/src/theme-monokai.js



# Our JS application
app.js:
  src: src/**/*.js
  dest: build/
  name: app.js
  babel-config:
    modules: common


# less => css
less:
  src: less/styles.less
  dest: build/


# examples
examples:
  src: examples/**/*.yaml
  dest: build/
  filename: examples.json
  settings:
    safe: true


# Plugins
# ---
# Plugin not here? Open an issue or submit a PR!
#
# Rebuild build/plugins.json with:
#
#    $ gulp update:plugins
#
plugins:
  dest: build/plugins.json
  list:
    - AndersMalmgren/Knockout.BindingConventions
    - AndersMalmgren/Knockout.Bootstrap
    - AndersMalmgren/Knockout.Combobox
    - AndersMalmgren/Knockout.Concurrency
    - CraigCav/Knockout-jqGridBinding
    - CraigCav/ko.datasource
    - Enome/knockknock
    - EntitySpaces/entityspaces.js
    - Igorbek/knockout.rx
    - Knockout-Contrib/Knockout-Validation
    - Knockout-Contrib/KoGrid
    - LucasLorentz/knockout.mapper
    - One-com/knockout-transformations
    - Supertext/knockout.groupedOptions
    - ZiadJ/knockoutjs-reactor
    - asaake/knockout-relational
    - billpull/knockout-bootstrap
    - brianmhunt/knockout-else
    - brianmhunt/knockout-es6-collections
    - brianmhunt/knockout-fast-foreach
    - brianmhunt/knockout-secure-binding
    - cameronprattedwards/ko-genius
    - civicsource/knockout-date-range-picker
    - civicsource/knockout-init
    - civicsource/knockout-inline-confirm
    - civicsource/knockout-integer
    - civicsource/knockout-money
    - civicsource/knockout-responsive
    - civicsource/knockout-spin
    - civicsource/knockout-transitions
    - cwdoh/Knockout-Binding-Selector
    - explorigin/knockout.model
    - finnsson/pagerjs
    - fru/observable.js
    - gaevoy/ko.widget
    - gvas/knockout-jqueryui
    - hoonzis/KoExtensions
    - hunterloftis/knockout.namespaces
    - ifandelse/Knockout.js-External-Template-Engine
    - jamesfoster/knockout.observableDictionary
    - johannds/hookpunch.js
    - kendo-labs/knockout-kendo
    - madcapnmckay/Knockout-UI
    - manuel-guilbault/ko.types
    - mbest/knockout-deferred-updates
    - mbest/knockout-repeat
    - mbest/knockout-switch-case
    - mbest/knockout.punches
    - mbest/knockout-table
    - mmjr/Knockout-Memento
    - mwiencek/knockout-arraytransforms
    - nescalante/knockout.contextmenu
    - onlyurei/knockout-logger-js
    - paglias/KnockoutApp
    - plcgi1/knockout.viewNavWithAcl
    - raheelshan/knockout-load
    - raheelshan/knockout-search
    - rniemeyer/knockout-amd-helpers
    - rniemeyer/knockout-classBindingProvider
    - rniemeyer/knockout-delegatedEvents
    - rniemeyer/knockout-interpolate
    - rniemeyer/knockout-kendo
    - rniemeyer/knockout-postbox
    - rniemeyer/knockout-sortable
    - romanych/ko.editables
    - seantimm/Knockout.LazyLoad
    - stevesanderson/knockout-projections
    - SteveSanderson/knockout-es5
    - thelinuxlich/knockout.live.plugin
    - thelinuxlich/knockout.model
    - thelinuxlich/knockout.underscore.plugin
    - tyrsius/ko-validate
