#
#   Configuration and settings for Knockout
#
banner: |
  // Knockout JavaScript library v<%= pkg.version %>
  // (c) Steven Sanderson - <%= pkg.homepage %>
  // License: <%= pkg.licenses[0].type %> (<%= pkg.licenses[0].url %>)

# Build scripts reside here
scriptsDir: build/fragments/

# knockout-latest[.debug].js goes here when compiled
buildDir: build/output/
build:
  main: knockout-latest.js
  debug: knockout-latest.debug.js

# Created in tagged 'release' versions
distDir: dist/
dist:
  min: knockout.min.js
  debug: knockout.debug.js

# These are injected into runner.template.html to produce runner.*.html
JQUERY_JS: node_modules/jquery/dist/jquery.js
# In due course, when upgrading to Jasmine 2.0, the spec/helper/
# files could be replaced with node_modules/jasmine-core/lib/jasmine-core
JASMINE_JS: spec/helpers/lib/jasmine.js
JASMINE_HTML_JS: spec/helpers/lib/jasmine-html.js
JASMINE_CSS: spec/helpers/lib/jasmine.css
# When Modernizr finally makes it into npm it could perhaps be installed
# that way. It is also notably in grunt-modernizr.
MODERNIZR_JS: spec/helpers/lib/modernizr.js

# Added to runner[.modernizr|.jquery].html
AUTOGEN_WARNING:  AUTOGENERATED FROM spec/helpers/runner.template.html

# Test files
node_spec: spec/spec.node.js
browser_spec: ./spec/helpers/specs.json

# Files that have their 'version' bumped
PACKAGE_FILES:
  - ./package.json
  - ./bower.json

# Closure compiler
closure_options:
  compilation_level: ADVANCED_OPTIMIZATIONS

# Files that have their trailing spaces checked on lint
trailingSpaceSources:
  - 'spec/*.{js,html,css,bat,ps1,sh}'
  - 'src/*.{js,html,css,bat,ps1,sh}'
  - 'build/fragments/*'

# Listening for changes
livereload_port: 35728
